import Head from 'next/head'
import Image from 'next/image'
import Layout, { siteTitle } from '../components/layout';
import Link from 'next/link';
import ultilStyles from '../styles/utils.module.css';

export default function Home() {
  return (
    <Layout home>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className={ultilStyles.headingMd}>
          <p>Sua descrição aqui</p>
          <p>
            (This is a sample website - you'll be building a site like this on {' '}
            <a href="https://nextjs.org/learn">our Next.js tutorial</a>.) 
          </p>
        </section>
      </Layout>
    
  )
}
